{{- $secretname := include "lookerbot.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lookerbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lookerbot.name" . }}
    helm.sh/chart: {{ include "lookerbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lookerbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lookerbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
            {{- if .Values.secret.enabled -}}
            {{- range $key, $val := .Values.secret.data }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretname }}
                  key: {{ $key }}
            {{- end}}
            {{- else -}}
            {{- range $key, $val := .Values.externalSecret.dataKeys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.name }}
                  key: {{ $val }}
            {{- end}}
            {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
  {{ toYaml .Values.resources | indent 12 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
